[package]
name = "top-type-sizes"
description = "Makes -Zprint-type-size more useful"
version = "0.1.1"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
eyre = "0.6.8"
nom = "7.1.3"
structopt = "0.3.26"

[dev-dependencies]
insta = "1.28.0"
